//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSANPHAM
    {
        public int MaChiTietSP { get; set; }
        public int MaSP { get; set; }
        public string KICHTHUOCMANHINH { get; set; }
        public string CONGNGHEMANHINH { get; set; }
        public string DOPHANGIAI { get; set; }
        public string TINHNANGMANGHINH { get; set; }
        public string TANSOQUET { get; set; }
        public string CAMERASAU { get; set; }
        public string QUAYPHIM { get; set; }
        public string CAMERATRUOC { get; set; }
        public string TINHNANGCAMERA { get; set; }
        public string HEDIEUHANH { get; set; }
        public string CHIP { get; set; }
        public string TOCDOCPU { get; set; }
        public string CHIPDOHOA { get; set; }
        public string RAM { get; set; }
        public string DUNGLUONG { get; set; }
        public string MANGDIDONG { get; set; }
        public string SIM { get; set; }
        public string WIFI { get; set; }
        public string CONGKETNOI { get; set; }
        public string DUNGLUONGPIN { get; set; }
        public string LOAIPIN { get; set; }
        public string HOTROSAC { get; set; }
        public string BAOMAT { get; set; }
        public string TINHNANGDACBIET { get; set; }
        public string KHANGNUOC { get; set; }
        public string THIETKE { get; set; }
        public string CHATLIEU { get; set; }
        public string KICHTHUOC { get; set; }
        public Nullable<int> BAOHANH { get; set; }
        public Nullable<System.DateTime> RAMAT { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
