//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHUKIENSACDUPHONG
    {
        public int MaCTPKSac { get; set; }
        public int MaSP { get; set; }
        public string HIEUSUAT { get; set; }
        public string DUNGLUONGPIN { get; set; }
        public string THOIGIANSAC { get; set; }
        public string NGUONVAO { get; set; }
        public string NGUONRA { get; set; }
        public string CONGNGHE { get; set; }
        public string KICHTHUOC { get; set; }
        public Nullable<int> BAOHANH { get; set; }
        public string KHOILUONG { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
