//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGNO
    {
        public int MaCongNo { get; set; }
        public int MaNCC { get; set; }
        public decimal SoTienNo { get; set; }
        public System.DateTime NgayCongNo { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
